version: '3.8'

services:
  mcp-atlassian:
    image: mcp-atlassian-local:latest
    container_name: mcp-atlassian
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["--transport", "streamable-http", "--port", "8000", "-v"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge